-- Default content from the archived Party-Games app (backup 2026-10-05).
INSERT INTO codes_words (word) VALUES
	('Leuchtturm'),
	('Regenschirm'),
	('Vulkan'),
	('Schmetterling'),
	('Kompass'),
	('Wasserfall'),
	('Pinguin'),
	('Feuerwehr'),
	('Schneeflocke'),
	('Drache'),
	('Marmelade'),
	('Teleskop'),
	('Kaktus'),
	('Achterbahn'),
	('Anker'),
	('Glühbirne'),
	('Lawine'),
	('Zauberer'),
	('Brezel'),
	('Karussell'),
	('Eisberg'),
	('Klavier'),
	('Roboter'),
	('Sonnenblume'),
	('Magnet'),
	('Skelett'),
	('Wikinger'),
	('Mikroskop'),
	('Fallschirm'),
	('Bumerang'),
	('Krokodil'),
	('Windmühle'),
	('Spinnennetz'),
	('Dinosaurier'),
	('Schatzkarte'),
	('Sandburg'),
	('Donner'),
	('Pyramide'),
	('Seifenblase'),
	('Akkordeon'),
	('Pirat'),
	('Bibliothek'),
	('Schatten'),
	('Honig'),
	('Wüste'),
	('Zirkus'),
	('Ritter'),
	('Spiegel'),
	('Rakete'),
	('Insel'),
	('Geist'),
	('Krone'),
	('Labyrinth'),
	('Ozean'),
	('Gletscher'),
	('Tresor'),
	('Falle'),
	('Nebel'),
	('Orchester'),
	('Riese'),
	('Schlüssel'),
	('Tunnel'),
	('Brücke'),
	('Wolke'),
	('Diamant'),
	('Hexe'),
	('Mumie'),
	('Nadel'),
	('Oase'),
	('Papagei'),
	('Quelle'),
	('Sirene'),
	('Teppich'),
	('Vampir'),
	('Wal'),
	('Zahnarzt'),
	('Astronaut'),
	('Delfin'),
	('Echo'),
	('Gondel'),
	('Hafen'),
	('Iglu'),
	('Känguru'),
	('Lupe'),
	('Marathon'),
	('Ninja'),
	('Regenbogen'),
	('Safari'),
	('Trampolin'),
	('Einhorn'),
	('Gewitter');

INSERT INTO duck_words (word) VALUES
	('Haus'),
	('Maus'),
	('Katze'),
	('Tatze'),
	('Hund'),
	('Mund'),
	('Baum'),
	('Traum'),
	('Licht'),
	('Gedicht'),
	('Hand'),
	('Wand'),
	('Stein'),
	('Bein'),
	('Tisch'),
	('Fisch'),
	('Nacht'),
	('Macht'),
	('Herz'),
	('Schmerz'),
	('Wein'),
	('Schein'),
	('Brot'),
	('Rot'),
	('Wald'),
	('Kalt'),
	('Sonne'),
	('Wonne'),
	('Regen'),
	('Segen'),
	('Blume'),
	('Krume'),
	('Stern'),
	('Kern'),
	('Buch'),
	('Tuch'),
	('Glück'),
	('Stück'),
	('Zeit'),
	('Leid'),
	('Wind'),
	('Kind'),
	('Berg'),
	('Zwerg'),
	('Graus'),
	('Laus'),
	('Bär'),
	('Meer'),
	('Tier'),
	('Bier'),
	('Schaf'),
	('Schlaf'),
	('Mauer'),
	('Trauer'),
	('Feder'),
	('Leder'),
	('Kette'),
	('Bette'),
	('Ente'),
	('Rente');

INSERT INTO most_likely_prompts (text) VALUES
	('Wer würde am ehesten im Lotto gewinnen und den Schein verlieren?'),
	('Wer würde am ehesten den eigenen Geburtstag vergessen?'),
	('Wer würde am ehesten bei einer Zombie-Apokalypse als Erstes draufgehen?'),
	('Wer würde am ehesten berühmt werden?'),
	('Wer würde am ehesten sein Handy in der Kneipe liegen lassen?'),
	('Wer würde am ehesten einen Marathon laufen?'),
	('Wer würde am ehesten eine eigene Kochshow bekommen?'),
	('Wer würde am ehesten beim Karaoke als Letztes die Bühne verlassen?'),
	('Wer würde am ehesten auswandern?'),
	('Wer würde am ehesten einen Streit mit einem Navi anfangen?'),
	('Wer würde am ehesten versehentlich in den falschen Zug steigen?'),
	('Wer würde am ehesten Millionär werden?'),
	('Wer würde am ehesten eine Nacht durchmachen und trotzdem pünktlich zur Arbeit kommen?'),
	('Wer würde am ehesten ein Haustier nach einem Essen benennen?'),
	('Wer würde am ehesten beim Escape Room in Panik geraten?'),
	('Wer würde am ehesten heimlich ein Reality-TV-Format schauen?'),
	('Wer würde am ehesten sein Passwort auf einen Zettel am Monitor kleben?'),
	('Wer würde am ehesten spontan ein Tattoo stechen lassen?'),
	('Wer würde am ehesten bei einem Quiz über sich selbst verlieren?'),
	('Wer würde am ehesten drei Tage ohne Handy überleben?'),
	('Wer würde am ehesten einen Podcast starten und nach zwei Folgen aufgeben?'),
	('Wer würde am ehesten im Urlaub die ganze Zeit am Pool liegen?'),
	('Wer würde am ehesten verschlafen und es auf den Wecker schieben?'),
	('Wer würde am ehesten mit Prominenten befreundet sein?'),
	('Wer würde am ehesten beim Monopoly einen Streit anfangen?'),
	('Wer würde am ehesten ein Selfie mit einem wilden Tier machen?'),
	('Wer würde am ehesten die Hochzeitsrede improvisieren?'),
	('Wer würde am ehesten den ganzen Kühlschrank leer essen?'),
	('Wer würde am ehesten aus Versehen "Ich liebe dich" zum Busfahrer sagen?'),
	('Wer würde am ehesten Bürgermeister werden?'),
	('Wer würde am ehesten bei einem Horrorfilm zuerst schreien?'),
	('Wer würde am ehesten eine Pflanze innerhalb einer Woche eingehen lassen?'),
	('Wer würde am ehesten einen Fremden im Zug volltexten?'),
	('Wer würde am ehesten sein ganzes Geld für Essen ausgeben?'),
	('Wer würde am ehesten beim Flunkyball das Team tragen?'),
	('Wer würde am ehesten versehentlich in eine Sekte geraten?'),
	('Wer würde am ehesten einen Nobelpreis gewinnen?'),
	('Wer würde am ehesten beim Wandern die Gruppe verlaufen lassen?'),
	('Wer würde am ehesten ein Jahr lang nur Nudeln essen können?'),
	('Wer würde am ehesten in einer Gameshow den Hauptgewinn ablehnen und weiterspielen?'),
	('Wer würde am ehesten beim ersten Date die Rechnung vergessen?'),
	('Wer würde am ehesten seine Schlüssel im Kühlschrank finden?'),
	('Wer würde am ehesten eine spontane Reise ohne Gepäck antreten?'),
	('Wer würde am ehesten im Meeting einschlafen?'),
	('Wer würde am ehesten heimlich mit dem Haustier reden?'),
	('Wer würde am ehesten einen Foodtruck eröffnen?'),
	('Wer würde am ehesten beim Aufbau eines Ikea-Regals aufgeben?'),
	('Wer würde am ehesten aus Versehen berühmt werden?'),
	('Wer würde am ehesten die Polizei rufen, weil das WLAN weg ist?'),
	('Wer würde am ehesten bei "Wer wird Millionär" den Publikumsjoker bei der ersten Frage ziehen?'),
	('Wer würde am ehesten sich selbst aus der Wohnung aussperren?'),
	('Wer würde am ehesten ein Doppelleben führen können?'),
	('Wer würde am ehesten den Abwasch eine Woche lang "einweichen" lassen?'),
	('Wer würde am ehesten beim Städtetrip nur Essen fotografieren?'),
	('Wer würde am ehesten einen Flohmarkt-Fund für ein Vermögen weiterverkaufen?'),
	('Wer würde am ehesten vergessen, wo das Auto geparkt ist?'),
	('Wer würde am ehesten mit 80 noch auf Festivals gehen?'),
	('Wer würde am ehesten heimlich die Deko vom Nachbarn geraderücken?'),
	('Wer würde am ehesten in einer Talentshow mit einem geheimen Talent überraschen?'),
	('Wer würde am ehesten die ganze Gruppe zum Lachen bringen, wenn es gerade ernst ist?');
